export const LOAD_DRIVERS_SUCCESS = "LOAD_DRIVERS_SUCCESS";
export const LOAD_RACES_SUCCESS = "LOAD_RACES_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const LOGOUT = 'USERS_LOGOUT';

export const LOAD_BOOKMARKS_SUCCESS = "LOAD_BOOKMARKS_SUCCESS";
export const LOAD_BOOKMARK_SUCCESS = "LOAD_BOOKMARK_SUCCESS";
export const CREATE_BOOKMARK_SUCCESS = "CREATE_BOOKMARK_SUCCESS";
export const UPDATE_BOOKMARK_SUCCESS = "UPDATE_BOOKMARK_SUCCESS";
export const DELETE_BOOKMARK_OPTIMISTIC = "DELETE_BOOKMARK_OPTIMISTIC";
